### ISSUE TITLE
Generated assembly doesn't work on MacOS

### ISSUE THREAD

**Issue by 0x1AE7F** [rtulip/haystack#118] opened 2022-12-05 15:28 UTC
Output:

```
---- ast::expr::tests::cast_u8 stdout ----
[CMD]: cargo r -q --release -- src/tests/type_check/cast_u8.hay
[CMD]: ./cast_u8
thread 'ast::expr::tests::cast_u8' panicked at 'called `Result::unwrap()` on an `Err` value: HayError { message: "Command Failed", kind: Error, loc: Loc { file: "src/tests/type_check/cast_u8", line: 1, span: 1..1 }, hints: [("Note", "Os { code: 2, kind: NotFound, message: \"No such file or directory\" }")] }', src/compiler/test_tools.rs:49:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rtulip** [comment] 2022-12-05 16:25
This will either require adding another implementation of `CodeGen` for different platforms. Or Haystack can transpile to `c` or `c++`. This would be a short term solution. It also raises questions about how to do things like reading from files, and things that I currently use syscalls for.

Ideally I'd like to switch to LLVM, but that's a much bigger project.

**Comment by rtulip** [comment] 2022-12-09 02:31
Closing this as a duplicate of #120 . We can look at any issues that come up once that's been fixed.

**Closed by rtulip** 2022-12-09 02:31 UTC
Labels: bug, effort_high, MacOS
